version: '3.8'
services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker 
      - POSTGRES_DB=airbnb


  api:
    build: ./Server
    restart: always
    ports:
      - "5174:5174"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:docker@database:5432/airbnb
      - NODE_ENV=production                     
    depends_on:
      - database

  frontend:
    build: ./Client
    ports:
      - "5173:5173"
    depends_on:
      - api
