version: '3.8'
services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker 
      - POSTGRES_DB=airbnb
    volumes:
      # copy the sql script to create tables
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
      - ./postgres-data:/var/lib/postgresql/data


  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "Team3@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - database

  api:
    build: ./Server
    restart: always
    ports:
      - "5174:5174"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:docker@database:5432/airbnb
      - NODE_ENV=production                     
    depends_on:
      - database

  frontend:
    build: ./Client
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres-data:
